input:
  kafka:
    addresses:
      - ${BROKERS}
    topics: ["events"]
    consumer_group: "s3-storage-sink-connector" # this refers to the consumer group id given to the pipe input, not the sink (s3 here)

pipeline:
  processors:
    # format each message by adding a newline (\n) at last (-1 index)
    # creates a clean JSON data block using new lines (.jsonl) on concatenation
    - insert_part:
        content: "\n"
        index: -1

output:
  aws_s3:
    endpoint: ${S3_ENDPOINT} # env
    force_path_style_urls: true
    bucket: ${S3_BUCKET} # env
    path: "${!now().ts_format(\"2006/01/02\")}/${!uuid_v4()}.json" # name of each message/object
    credentials:
      id: ${AWS_ACCESS_KEY_ID} # env
      secret: ${AWS_SECRET_ACCESS_KEY} # env
    region: "us-east-1" # dummy region for compatibility

    batching:
      count: 1000  # batch 1000 messages
      period: 10s  # or for 10 seconds whichever happens first
      processors:
        - archive:
            format: concatenate # concat all the messages (already added newlines in pipeline)
        - compress:
            algorithm: gzip # compress for easier storage
